name: Run Encrypted Script and Push Output

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: pip install cryptography requests
      
      - name: Run encrypted script with repo sync
        env:
          FERNET_KEY: ${{ secrets.FERNET_KEY }}
          PRIVATE_REPO_URL: ${{ secrets.PRIVATE_REPO_URL }}
         
        run: python runner.py
